### ISSUE TITLE
Bug in closing the jdbc connection

### ISSUE THREAD

**Issue by mscholzj** [jottyfan/jooqFaces#1]
Hello.

**Problem:** 
Using postgresql as db i keep getting unclosed connections. (select * from pg_stat_activity; \watch 1)
After some time some of them are closed again but others remain open resulting in full pool.

**The cause**
You open a connection here, pass it to jooq and put it in the facescontext map:

https://github.com/jottyfan/jooqFaces/blob/a7d80e90333c8cf7b1eafe6481709fe391356dd9/src/main/java/de/jooqFaces/JooqFacesRestoreViewPhaseListener.java#L102-L105

Then you close it again here:

https://github.com/jottyfan/jooqFaces/blob/a7d80e90333c8cf7b1eafe6481709fe391356dd9/src/main/java/de/jooqFaces/JooqFacesRenderResponsePhaseListener.java#L24-L26

[Jooq Docs state](https://www.jooq.org/doc/3.10/manual/sql-building/dsl-context/connection-vs-datasource/): The normal operation mode is to provide a Configuration with a JDBC Connection, whose lifecycle you will control yourself. This means that jOOQ will not actively close connections, rollback or commit transactions. 

[The close method of the dsl context is described as:](https://www.jooq.org/javadoc/3.9.0/org/jooq/DSLContext.html#close--) Some DSLContext constructors, such as DSL.using(String), DSL.using(String, Properties), or DSL.using(String, String, String) allocate a Connection resource, which is inaccessible to the outside of the DSLContext implementation. Proper resource management must thus be done via this close() method.

The pass connection is not closed using this method.
Try a System.out.println(dslContext.configuration().connectionProvider().acquire().isClosed()); after calling the close method.

I have, temporarily, extended the response listener and additionally call the dslContext.configuration().connectionProvider().acquire().close(); method. But this should be done by your listener itself.

_(I used the 0.0.6-Snapshot, but the code did not change in the newest version.)_

----

If you dont pass a connection to the DSL context but let it create the connection then the close method will also close the connection.
``` java
DSLContext dsl = DSL.using(jdbcUrl + "?user=" + username + "&password=" + password);
...
dsl.close();
```

Also, using the try-with-resources method works as expected. It closes the connection automatically:

``` java
// using autoclose
try(Connection conn = DriverManager.getConnection(jdbcUrl, username, password)) {
    DSLContext dsl = DSL.using(conn, SQLDialect.POSTGRES);
    dsl.close();
}
```

**Comment by jottyfan** [comment]
Thank you very much for that detailed bug report. I'll have a look at that.

**Comment by jottyfan** [comment]
see https://github.com/jottyfan/jooqFaces/releases/tag/closing
